# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-25 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_userinfo_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='defeat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='draw',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='score',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='victory',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Victory',
        ),
    ]
